'use client';

import React, { useState } from 'react';
import { Search, Map, Zap, Target, ArrowRight, ExternalLink, PlayCircle } from 'lucide-react';

const NxtStepHome = () => {
  const [activeTab, setActiveTab] = useState('roadmap');

  return (
    <div className="min-h-screen bg-white font-sans text-slate-900">
      {/* --- NAVIGATION --- */}
      <nav className="flex items-center justify-between px-8 py-6 border-b border-slate-100">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-orange-600 rounded-lg flex items-center justify-center text-white font-bold italic">N</div>
          <span className="text-xl font-bold tracking-tight uppercase">NxtStep</span>
        </div>
        <div className="hidden md:flex gap-8 text-sm font-medium text-slate-600">
          <a href="#" className="hover:text-orange-600 transition">Roadmaps</a>
          <a href="#" className="hover:text-orange-600 transition">AI Coach</a>
          <a href="#" className="hover:text-orange-600 transition">Skill Pivot</a>
          <a href="#" className="hover:text-orange-600 transition">Dashboard</a>
        </div>
        <button className="bg-orange-600 text-white px-6 py-2.5 rounded-full font-bold text-sm hover:bg-orange-700 transition shadow-lg shadow-orange-200">
          Get Started
        </button>
      </nav>

      {/* --- HERO SECTION --- */}
      <header className="relative px-8 py-20 bg-slate-50 overflow-hidden">
        <div className="max-w-6xl mx-auto grid md:grid-cols-2 gap-12 items-center">
          <div className="z-10">
            <div className="flex items-center gap-2 text-orange-600 font-bold text-sm uppercase tracking-widest mb-4">
              <Zap size={16} fill="currentColor" />
              <span>AI-Powered Career Discovery</span>
            </div>
            <h1 className="text-7xl font-black leading-[0.9] mb-6 tracking-tighter uppercase italic">
              Find Your <br /> 
              <span className="text-orange-600">Next Level*</span>
            </h1>
            <p className="text-lg text-slate-600 mb-8 max-w-md leading-relaxed">
              Stop guessing your future. Get AI-generated roadmaps, real-world mini-challenges, and skill-pivot maps designed for the modern student.
            </p>
            <div className="flex gap-4">
              <button className="bg-slate-900 text-white px-8 py-4 rounded-xl font-bold flex items-center gap-2 hover:scale-105 transition">
                Start Exploring <ArrowRight size={20} />
              </button>
              <button className="bg-white border-2 border-slate-200 px-8 py-4 rounded-xl font-bold flex items-center gap-2 hover:bg-slate-50 transition">
                <PlayCircle size={20} /> Watch Demo
              </button>
            </div>
          </div>
          <div className="relative">
            {/* The "Surfing" style overlapping image layout */}
            <div className="relative rounded-3xl overflow-hidden shadow-2xl border-8 border-white">
              <img 
                src="https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80" 
                alt="Students collaborating" 
                className="w-full h-[450px] object-cover"
              />
              <div className="absolute bottom-6 right-6 bg-white p-6 rounded-2xl shadow-xl max-w-[240px]">
                <div className="flex gap-1 mb-2 text-orange-500">
                  {[...Array(5)].map((_, i) => <Target key={i} size={16} fill="currentColor" />)}
                </div>
                <h3 className="font-bold text-lg leading-tight">AI Skills Match</h3>
                <p className="text-xs text-slate-500 mt-2">"NxtStep accurately mapped my love for art to a high-paying UX career."</p>
                <p className="text-xs font-bold mt-3">— Sarah, Design Student</p>
              </div>
            </div>
          </div>
        </div>
        {/* Background Decorative Text */}
        <div className="absolute -bottom-10 left-0 w-full opacity-[0.03] select-none pointer-events-none">
          <h2 className="text-[250px] font-black italic leading-none whitespace-nowrap">FUTURE PROOF</h2>
        </div>
      </header>

      {/* --- INTERACTIVE ROADMAP PREVIEW --- */}
      <section className="py-24 px-8 max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-black uppercase italic mb-4">Your Skill-Gaining Roadmap</h2>
          <p className="text-slate-500">Interactive paths generated by AI to take you from beginner to pro.</p>
        </div>

        <div className="bg-yellow-50 rounded-[40px] p-12 border-2 border-yellow-100 relative overflow-hidden">
          {/* Main Spine */}
          <div className="absolute left-1/2 top-0 bottom-0 w-1 bg-blue-500 hidden md:block opacity-30"></div>

          <div className="relative grid grid-cols-1 md:grid-cols-2 gap-y-16 gap-x-32 items-center">
            
            {/* Left Node: Prerequisite */}
            <div className="flex flex-col items-end text-right order-1">
              <div className="grid grid-cols-2 gap-3 mb-6">
                {['Python', 'C++', 'Java', 'Go'].map(lang => (
                  <div key={lang} className="bg-yellow-400 border-2 border-slate-900 px-4 py-2 rounded-lg font-bold text-sm shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
                    {lang}
                  </div>
                ))}
              </div>
              <p className="text-xs font-bold text-blue-600 uppercase tracking-widest">Step 01: Basics</p>
            </div>

            {/* Right Node: Core Knowledge */}
            <div className="order-2">
              <div className="bg-yellow-300 border-4 border-slate-900 p-6 rounded-2xl shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] max-w-xs">
                <h4 className="font-black text-xl mb-2">Pick a Language</h4>
                <div className="h-1 w-12 bg-slate-900 mb-4"></div>
                <ul className="space-y-2">
                  <li className="flex items-center gap-2 text-sm font-bold opacity-70 italic hover:opacity-100 cursor-pointer">
                    <ExternalLink size={14} /> Language Syntax
                  </li>
                  <li className="flex items-center gap-2 text-sm font-bold opacity-70 italic hover:opacity-100 cursor-pointer">
                    <ExternalLink size={14} /> Logic Flow
                  </li>
                </ul>
              </div>
            </div>

            {/* Middle Prompt: Mini-Challenge */}
            <div className="md:col-span-2 flex justify-center order-3">
              <div className="bg-white border-2 border-orange-500 p-8 rounded-3xl shadow-2xl max-w-2xl w-full text-center relative">
                <div className="absolute -top-4 left-1/2 -translate-x-1/2 bg-orange-600 text-white px-4 py-1 rounded-full text-xs font-bold uppercase tracking-widest">
                  5-Min Mini Challenge
                </div>
                <h3 className="text-2xl font-black mb-4 uppercase">Design a Logo for 'Meow & Mugs'</h3>
                <p className="text-slate-600 mb-6 italic">"A local cat café needs a cozy but modern vibe. Which font-style would you pick and why?"</p>
                <div className="flex justify-center gap-4">
                  <button className="bg-slate-100 hover:bg-orange-100 border-2 border-slate-200 py-3 px-6 rounded-xl font-bold transition">Serif (Classic)</button>
                  <button className="bg-slate-100 hover:bg-orange-100 border-2 border-slate-200 py-3 px-6 rounded-xl font-bold transition">Sans (Modern)</button>
                </div>
              </div>
            </div>

          </div>
        </div>
      </section>

      {/* --- STATS BAR --- */}
      <footer className="bg-orange-600 py-10 overflow-hidden relative">
        <div className="flex justify-around items-center max-w-6xl mx-auto text-white">
          <div className="text-center">
            <h4 className="text-4xl font-black leading-none">120k+</h4>
            <p className="text-xs font-bold uppercase tracking-widest opacity-80 mt-2">Active Students</p>
          </div>
          <div className="text-center border-x border-orange-500 px-20">
            <h4 className="text-4xl font-black leading-none">95%</h4>
            <p className="text-xs font-bold uppercase tracking-widest opacity-80 mt-2">Placement Rate</p>
          </div>
          <div className="text-center">
            <h4 className="text-4xl font-black leading-none">4.9/5</h4>
            <p className="text-xs font-bold uppercase tracking-widest opacity-80 mt-2">AI Accuracy</p>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default NxtStepHome;